# The URL the site will be built for.
# Served via GitHub Pages with a custom domain.
base_url = "https://onewireout.com"

title = "One Wire Out"
author = "F41N"
description = "I make things for myself, I put them here."

theme = "zola-grayscale"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
